name: CI CD 4
on:
  push:
    branches: [ percobaan-1 ]

jobs:
  deploy:
    name: SCP files to server
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: SCP files via ssh key
        uses: appleboy/scp-action@master
        env:
          USERNAME: ${{ secrets.SSH_USERNAME }}
          HOST: ${{ secrets.SSH_HOST }}
          PASSWORD: ${{ secrets.FTP_PASSWORD }}
        with:
          source: '*'
          target: '~/public_html/apriana'