name: CI CD LAGI
on:
  push:
    branches: [ percobaan-1 ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      BASEURL: ''
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@4.1.0
        with:
          server: ftp.limasakti.co.id
          username: aprianaftp@limasakti.co.id
          password: ${{secrets.FTP_PASSWORD}}