name: CI CD LAGI
on:
  push:
    branches: [ percobaan-1 ]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Get Latest Code
        uses: actions/checkout@v2
      - name: Sync Files
        uses: easingthemes/ssh-deploy@v2.1.5
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
          REMOTE_HOST: 223.27.147.38
          REMOTE_USER: researchlbs