name: CI CD 4
on:
  push:
    branches: [ percobaan-1 ]

jobs:
  deploy:
    name: SCP files to server
    runs-on: ubuntu-latest
    steps:
      - name: SCP files via ssh key
        uses: appleboy/scp-action@master
        env:
          USERNAME: ${{ secrets.SSH_USERNAME }}
          HOST: ${{ secrets.SSH_HOST }}
          KEY: ${{ secrets.SSH_KEY }}
        with:
          source: './*'
          target: '/home/researchlbs/public_html/apriana'