name: Identifier Name
on:
  push:
    branches: [ percobaan-1 ]

jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: gBk~558yQMMz
        source: "*"
        target: "~/public_html/apriana"