name: Identifier Name
on:
  push:
    branches: [ percobaan-1 ]

jobs:
  build:
    name: deploy
    runs-on: ubuntu-latest
    steps:
    - name: checks-out repository 
      uses: actions/checkout@master

    - name: Create folder
      run: mkdir deploy && cp -R ./* deploy

    - name: check folder is created
      run: ls delpoy

    - name: copy file via ssh password
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        username: ${{ secrets.SSH_USERNAME }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        source: "*"
        target: "~/public_html/apriana"